[package]
authors = ["aarbuzov"]
name = "zmodem"
version = "0.1.0"

[dependencies]
clap = "2.21.1"
crc = "1.4.0"
env_logger = "0.4.2"
hex = "0.2.0"
hexdump = "0.1.0"
log = "0.3.7"

[dev-dependencies]
lazy_static = "0.2.4"
rand = "0.3.15"
